### ISSUE TITLE
Octoprint 1.4.0rc1 support

### ISSUE THREAD

**Issue by sebaminguez** [malnvenshorn/OctoPrint-FilamentManager#183]
**Describe the bug**
Plugin doesn't work on Octoprint Release 1.4.0rc1

**Steps to reproduce**
1. Update octoprint to 1.4.0rc1
2. Verify that plugin is disabled 

**Expected behavior**
Plugin still enabled

**Did the same happen when all other 3rd party plugins are disabled?**
Yes, 

**Log file**
`
octoprint.plugin.core - ERROR - Exception while initializing plugin filamentmanager, disabling it
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/plugin/core.py", line 1439, in initialize_implementation
    implementation.initialize()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_filamentmanager/__init__.py", line 53, in initialize
    self.filamentOdometer.set_g90_extruder(self._settings.getBoolean(["feature", "g90InfluencesExtruder"]))
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/plugin/__init__.py", line 521, in __getattr__
    orig_func = decorator(orig_func)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/util/__init__.py", line 134, in decorator
    func.__qualname__ = to_native_str('warning_decorator_factory')
AttributeError: 'instancemethod' object has no attribute '__qualname__'
`
[octoprint.log](https://github.com/malnvenshorn/OctoPrint-FilamentManager/files/3889227/octoprint.log)

**Comment by sebaminguez** [comment]
Solved on the octoprint side https://github.com/foosel/OctoPrint/issues/3347
